name: "New infra pipeline"
 
on:
  push:
    branches: [ "main", "feature/**" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      working_directory:
        description: "Path to Terraform"
        required: true
        default: "rg"
 
permissions:
  id-token: write
  contents: read
 
jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: windows-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      WORK_DIR: ${{ github.event.inputs.working_directory || 'rg' }}
 
    steps:
      - name: Checkout
        uses: actions/checkout@v4
 
      - name: Terraform Init & Plan
        shell: pwsh
        run: |
          cd ${{ env.WORK_DIR }}
          terraform init
          terraform plan -out=tfplan
        
      - name: Upload Plan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: ${{ env.WORK_DIR }}/tfplan
 
  terraform-apply:
    name: Terraform Apply
    needs: terraform-plan
    if: github.ref == 'refs/heads/main' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
    runs-on: windows-latest
    environment: dev
    
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      WORK_DIR: ${{ github.event.inputs.working_directory || 'rg' }}
 
    steps:
      - name: Checkout
        uses: actions/checkout@v4
 
      - name: Download Plan Artifact
        uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: ${{ env.WORK_DIR }}
 
      - name: Terraform Init & Apply
        shell: pwsh # 
        run: |
          cd ${{ env.WORK_DIR }}
          terraform init
          terraform apply -auto-approve tfplan
